INITIAL_HAND=5
CLOCK_DRAW=2
HAND_LIMIT=7

FRONT_STAGE=[0,1,2]
BACK_STAGE=[3,4]
STAGE_SIZE=len(FRONT_STAGE)+len(BACK_STAGE)
INIT_CLOCK_LIMIT=7
INIT_LEVEL_LIMIT=4
REFRESH_TRIGGER_REMAIN=43#0

# Rule Damage
REFRESH_RULE_DAMAGE=1